CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(50) PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    saldo INT DEFAULT 0,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rooms (
    id VARCHAR(50) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    fee INT NOT NULL DEFAULT 0,
    pp INT NOT NULL DEFAULT 0,
    status VARCHAR(20) DEFAULT 'open',
    inProgress TINYINT(1) DEFAULT 0,
    winnerId VARCHAR(50) DEFAULT NULL,
    winnerSetAt DATETIME DEFAULT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS room_players (
    id INT AUTO_INCREMENT PRIMARY KEY,
    roomId VARCHAR(50) NOT NULL,
    userId VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    joinedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (roomId) REFERENCES rooms(id) ON DELETE CASCADE,
    FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS messages (
    id VARCHAR(50) PRIMARY KEY,
    roomId VARCHAR(50) NOT NULL,
    senderName VARCHAR(100) NOT NULL,
    text TEXT,
    image VARCHAR(255) DEFAULT NULL,
    isSystem TINYINT(1) DEFAULT 0,
    time DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (roomId) REFERENCES rooms(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS message_seen (
    id INT AUTO_INCREMENT PRIMARY KEY,
    messageId VARCHAR(50) NOT NULL,
    userName VARCHAR(100) NOT NULL,
    FOREIGN KEY (messageId) REFERENCES messages(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS transactions (
    id VARCHAR(50) PRIMARY KEY,
    userId VARCHAR(50),
    userName VARCHAR(100) NOT NULL,
    type VARCHAR(30) NOT NULL,
    amount INT DEFAULT 0,
    bukti VARCHAR(255) DEFAULT NULL,
    rekening VARCHAR(255) DEFAULT NULL,
    roomName VARCHAR(100) DEFAULT NULL,
    roomId VARCHAR(50) DEFAULT NULL,
    fee INT DEFAULT NULL,
    pp INT DEFAULT NULL,
    status VARCHAR(20) DEFAULT 'pending',
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (userId) REFERENCES users(id) ON DELETE SET NULL
);
